kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: eliopeli
  labels:
    app: eliopeli-prod
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: eliopeli/eliopeli:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local