kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: eliopeli
  labels:
    app: eliopeli
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: eeroHY/eliopeli:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
