#openshift config for nginx -> used n prod/staging deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: eliopeli
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://localhost:4173;
            proxy_set_header Host $host;
        }
    }